[package]
name = "jrnii"
version = "0.1.0"
authors = ["Annie Gao <qijia.gao@mail.utoronto.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0.1"